# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Winn.io
email: winn.greg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Greg Winn I am a web developer, specializing in web application development. Take a look at some of my projects, then drop me a line.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://winn.io" # the base hostname & protocol for your site
twitter_username: gregwinn
github_username:  gregwinn

# Build settings
markdown: kramdown
